set(_CATKIN_CURRENT_PACKAGE "sign")
set(sign_VERSION "0.0.0")
set(sign_MAINTAINER "thanh <thanh@todo.todo>")
set(sign_PACKAGE_FORMAT "2")
set(sign_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(sign_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(sign_BUILDTOOL_DEPENDS "catkin")
set(sign_BUILDTOOL_EXPORT_DEPENDS )
set(sign_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(sign_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(sign_TEST_DEPENDS )
set(sign_DOC_DEPENDS )
set(sign_URL_WEBSITE "")
set(sign_URL_BUGTRACKER "")
set(sign_URL_REPOSITORY "")
set(sign_DEPRECATED "")